//! Differential test: the records subql derives from a real CDC row image
//! must equal the records the loader's own SQL returns for the same rows.
//!
//! subql evaluates a [`RecordDescription`] against a row image and renders
//! each cell to the text a record is keyed on. rls2fga renders the same
//! records in SQL, with Postgres doing the rendering. Those two renderings
//! are written in different languages by different crates, so nothing but
//! running both against one database says they agree.
//!
//! The failure this catches is silent. A key rendered even slightly
//! differently, an integer with a thousands separator or a UUID in upper
//! case, names an object or a subject the store never contains, so every
//! answer about it is wrong and nothing reports a problem.
//!
//! rls2fga already proves its descriptions agree with its SQL, using its
//! own value rendering. That oracle stops where subql's adapter begins,
//! which is exactly the seam this covers.
//!
//! Docker-backed. Run with:
//!
//! ```sh
//! cargo test --test visibility_records_parity \
//!     --features "visibility-records executor-diesel-postgres" -- --ignored --nocapture
//! ```

#![cfg(all(feature = "visibility-records", feature = "executor-diesel-postgres"))]
#![allow(clippy::unwrap_used)]

mod common;

use std::collections::BTreeSet;

use diesel::prelude::*;
use diesel::sql_types::Text;
use diesel::{sql_query, PgConnection, QueryableByName};
use rls2fga::classifier::patterns::ConfidenceLevel;
use rls2fga::generator::records::{Record, RecordDerivation, RecordDescription};
use rls2fga::translator::TranslatorBuilder;
use sqlparser::dialect::PostgreSqlDialect;
use subql::backend::{CdcEvent, RowKind};
use subql::visibility::records::{is_evaluable, records_from_row_view};
use subql::visibility::store::StoreShapes;
use subql::visibility::EventRow;
use subql::{catalog_helpers, parse_wal2json_v2, MessageV2, ParserDB};

const SLOT: &str = "records_parity_slot";

/// The schema both sides read. Kept to statements `ParserDB` and rls2fga
/// both parse, so one string is the single source for the catalog, the
/// translation and the database.
///
/// Between them the four shapes cover every spelling `render_text` claims:
/// a `UUID` object key, an `INTEGER` and a `BIGINT` one, a `TEXT` subject,
/// a JSON path subject, a literal subject, and a boolean guard.
const SCHEMA: &str = "
CREATE TABLE docs (id UUID PRIMARY KEY, owner_id TEXT, is_public BOOLEAN);
CREATE TABLE notes (id BIGINT PRIMARY KEY, owner_id TEXT);
CREATE TABLE cards (id INTEGER PRIMARY KEY, meta JSONB);
ALTER TABLE docs ENABLE ROW LEVEL SECURITY;
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE cards ENABLE ROW LEVEL SECURITY;
CREATE POLICY docs_owner ON docs FOR SELECT USING (owner_id = current_user);
CREATE POLICY docs_public ON docs FOR SELECT USING (is_public);
CREATE POLICY notes_owner ON notes FOR SELECT USING (owner_id = current_user);
CREATE POLICY cards_owner ON cards FOR SELECT USING (meta->>'owner' = current_user);
";

// The typed schema for seeding. One `table!` per table above, so a column
// renamed in `SCHEMA` and not here is a compile error rather than a
// runtime one.
diesel::table! {
    docs (id) {
        id -> diesel::sql_types::Uuid,
        owner_id -> diesel::sql_types::Nullable<diesel::sql_types::Text>,
        is_public -> diesel::sql_types::Nullable<diesel::sql_types::Bool>,
    }
}

diesel::table! {
    notes (id) {
        id -> diesel::sql_types::BigInt,
        owner_id -> diesel::sql_types::Nullable<diesel::sql_types::Text>,
    }
}

diesel::table! {
    cards (id) {
        id -> diesel::sql_types::Integer,
        meta -> diesel::sql_types::Nullable<diesel::sql_types::Jsonb>,
    }
}

/// One `(object, relation, subject)` row of a tuple query.
///
/// The query text is generated by rls2fga at run time, so no `table!`
/// describes it and the typed DSL cannot express it. Naming the three
/// columns and their SQL types here is what keeps the raw statement from
/// drifting: a tuple query that stopped selecting `subject` would fail to
/// load rather than silently return less.
#[derive(QueryableByName)]
struct TupleRow {
    #[diesel(sql_type = Text)]
    object: String,
    #[diesel(sql_type = Text)]
    relation: String,
    #[diesel(sql_type = Text)]
    subject: String,
}

/// DDL, which the typed DSL does not express.
fn ddl(conn: &mut PgConnection, statement: &str) {
    sql_query(statement).execute(conn).expect(statement);
}

fn create_schema(conn: &mut PgConnection) {
    for statement in SCHEMA.split(';').filter(|s| !s.trim().is_empty()) {
        ddl(conn, statement);
    }
    // The update phase reads the previous image, which Postgres sends in
    // full only under FULL. Without this the difference is refused rather
    // than wrong, which would make that half of the test vacuous.
    for table in ["docs", "notes", "cards"] {
        ddl(conn, &format!("ALTER TABLE {table} REPLICA IDENTITY FULL"));
    }
}

fn uuid(text: &str) -> uuid::Uuid {
    uuid::Uuid::parse_str(text).unwrap()
}

/// Rows chosen so each one answers a question the next cannot.
fn seed(conn: &mut PgConnection) {
    diesel::insert_into(docs::table)
        .values(vec![
            // Renders as a UUID, grants its owner, and is not public.
            (
                docs::id.eq(uuid("550e8400-e29b-41d4-a716-446655440000")),
                docs::owner_id.eq(Some("alice")),
                docs::is_public.eq(Some(false)),
            ),
            // A NULL owner grants nobody, and the public flag grants the
            // wildcard, so one row exercises both a failing and a passing
            // guard at once.
            (
                docs::id.eq(uuid("6ba7b810-9dad-11d1-80b4-00c04fd430c8")),
                docs::owner_id.eq(None::<&str>),
                docs::is_public.eq(Some(true)),
            ),
            // Punctuation a naive renderer might quote or escape. The colon
            // is the record separator, so a subject containing one is the
            // case most likely to be mangled on one side only.
            (
                docs::id.eq(uuid("00000000-0000-4000-8000-000000000001")),
                docs::owner_id.eq(Some("o'brien:x \"y\" ünïcode")),
                docs::is_public.eq(Some(false)),
            ),
        ])
        .execute(conn)
        .unwrap();

    diesel::insert_into(notes::table)
        .values(vec![
            // The extremes of the range subql decodes into `Value::Int`.
            (notes::id.eq(i64::MAX), notes::owner_id.eq(Some("bob"))),
            (notes::id.eq(i64::MIN), notes::owner_id.eq(Some("carol"))),
            (notes::id.eq(0_i64), notes::owner_id.eq(Some("dave"))),
        ])
        .execute(conn)
        .unwrap();

    diesel::insert_into(cards::table)
        .values(vec![
            // A string leaf reads as its contents, not its quoted form.
            (
                cards::id.eq(1),
                cards::meta.eq(Some(serde_json::json!({"owner": "erin"}))),
            ),
            // A number and a boolean leaf: `->>` renders both as text, and
            // so must the adapter.
            (
                cards::id.eq(2),
                cards::meta.eq(Some(serde_json::json!({"owner": 42}))),
            ),
            (
                cards::id.eq(3),
                cards::meta.eq(Some(serde_json::json!({"owner": true}))),
            ),
            // JSON null and an absent key both grant nobody.
            (
                cards::id.eq(4),
                cards::meta.eq(Some(serde_json::json!({"owner": null}))),
            ),
            (
                cards::id.eq(5),
                cards::meta.eq(Some(serde_json::json!({"other": "frank"}))),
            ),
            (cards::id.eq(6), cards::meta.eq(None::<serde_json::Value>)),
        ])
        .execute(conn)
        .unwrap();
}

/// What the loader would write, straight from the database.
fn records_from_sql(conn: &mut PgConnection, sql: &str) -> BTreeSet<Record> {
    sql_query(sql)
        .load::<TupleRow>(conn)
        .unwrap_or_else(|error| panic!("tuple query failed: {error}\n{sql}"))
        .into_iter()
        .map(|row| Record {
            object: row.object,
            relation: row.relation,
            subject: row.subject,
        })
        .collect()
}

fn drain(conn: &mut PgConnection) -> Vec<MessageV2> {
    common::drain_slot(conn, SLOT)
        .iter()
        .flat_map(|line| parse_wal2json_v2(line.as_bytes()).unwrap())
        .collect()
}

/// Every record `description` implies over the `row` image of each event on
/// its table.
fn records_from_events(
    events: &[MessageV2],
    description: &RecordDescription,
    catalog: &ParserDB,
    row: RowKind,
) -> BTreeSet<Record> {
    let RecordDerivation::FromRow { table, .. } = &description.derivation else {
        panic!("only a row-derived description reaches here");
    };
    let table = catalog_helpers::table_id(catalog, table).expect("the table is in the catalog");

    let mut out = BTreeSet::new();
    for event in events {
        if event.table_id(catalog) != table {
            continue;
        }
        let Some(view) = EventRow::new(event, catalog, row) else {
            continue;
        };
        out.extend(
            records_from_row_view(description, &view, catalog).unwrap_or_else(|error| {
                panic!("subql refused a row it should read: {error}\n{description:#?}")
            }),
        );
    }
    out
}

/// The descriptions rls2fga emits for `SCHEMA`, paired with the SQL that
/// loads each one.
fn shapes(catalog: &ParserDB) -> Vec<(String, RecordDescription)> {
    let outputs = TranslatorBuilder::new()
        .with_min_confidence(ConfidenceLevel::B)
        .build()
        .translate(catalog)
        .outputs_accepting_gaps();
    outputs
        .tuple_queries()
        .into_iter()
        .filter_map(|query| {
            let description = query.description?;
            (is_evaluable(&description)
                && matches!(description.derivation, RecordDerivation::FromRow { .. }))
            .then_some((query.sql, description))
        })
        .collect()
}

#[test]
#[ignore = "requires Docker"]
fn every_record_a_row_implies_matches_the_query_that_loads_it() {
    common::assert_docker_available();
    let container = common::pg_with_wal2json();
    let mut pg = common::pg_connect(common::pg_port(&container));

    create_schema(&mut pg);
    common::create_slot(&mut pg, SLOT);
    seed(&mut pg);

    let catalog = ParserDB::parse::<PostgreSqlDialect>(SCHEMA).unwrap();
    let events = drain(&mut pg);
    assert!(!events.is_empty(), "the slot carried no row events");

    let shapes = shapes(&catalog);
    assert_eq!(shapes.len(), 4, "the schema should emit four shapes");

    let mut compared = 0usize;
    for (sql, description) in &shapes {
        let from_sql = records_from_sql(&mut pg, sql);
        let from_rows = records_from_events(&events, description, &catalog, RowKind::New);
        assert_eq!(
            from_rows, from_sql,
            "subql's records diverge from the loader's for:\n{sql}"
        );
        compared += from_sql.len();
    }
    assert!(compared >= 8, "only {compared} records compared");
}

#[test]
#[ignore = "requires Docker"]
fn the_difference_a_change_reports_matches_what_the_loader_would_reload() {
    common::assert_docker_available();
    let container = common::pg_with_wal2json();
    let mut pg = common::pg_connect(common::pg_port(&container));

    create_schema(&mut pg);
    common::create_slot(&mut pg, SLOT);
    seed(&mut pg);
    drain(&mut pg);

    let catalog = ParserDB::parse::<PostgreSqlDialect>(SCHEMA).unwrap();
    let shapes = shapes(&catalog);
    let before: BTreeSet<Record> = shapes
        .iter()
        .flat_map(|(sql, _)| records_from_sql(&mut pg, sql))
        .collect();

    // One row changes hands, one loses its grant, one gains one, and one is
    // removed outright, so the difference has to carry all four directions.
    diesel::update(docs::table.find(uuid("550e8400-e29b-41d4-a716-446655440000")))
        .set(docs::owner_id.eq(Some("zara")))
        .execute(&mut pg)
        .unwrap();
    diesel::update(notes::table.find(i64::MAX))
        .set(notes::owner_id.eq(None::<&str>))
        .execute(&mut pg)
        .unwrap();
    diesel::update(cards::table.find(5))
        .set(cards::meta.eq(Some(serde_json::json!({"owner": "gina"}))))
        .execute(&mut pg)
        .unwrap();
    diesel::delete(notes::table.find(0_i64))
        .execute(&mut pg)
        .unwrap();

    let events = drain(&mut pg);
    assert_eq!(events.len(), 4, "one event per statement");

    let after: BTreeSet<Record> = shapes
        .iter()
        .flat_map(|(sql, _)| records_from_sql(&mut pg, sql))
        .collect();

    let relations = TranslatorBuilder::new()
        .with_min_confidence(ConfidenceLevel::B)
        .build()
        .translate(&catalog)
        .relations();
    let store = StoreShapes::new(
        ParserDB::parse::<PostgreSqlDialect>(SCHEMA).unwrap(),
        &relations,
    );
    assert!(store.uncovered().is_empty(), "{:?}", store.uncovered());

    let mut added = BTreeSet::new();
    let mut removed = BTreeSet::new();
    for event in &events {
        let diff = store
            .diff(event)
            .unwrap_or_else(|error| panic!("the difference was refused: {error}"));
        added.extend(diff.added);
        removed.extend(diff.removed);
        assert!(diff.requeries.is_empty(), "no shape here needs a query");
    }

    assert_eq!(
        added,
        after.difference(&before).cloned().collect::<BTreeSet<_>>(),
        "what the rows say was added is not what the loader would now write"
    );
    assert_eq!(
        removed,
        before.difference(&after).cloned().collect::<BTreeSet<_>>(),
        "what the rows say was removed is not what the loader would now drop"
    );
    assert!(
        !added.is_empty() && !removed.is_empty(),
        "vacuous comparison"
    );
}
