//! Differential test: the records subql derives from a real CDC row image
//! must equal the records the loader's own SQL returns for the same rows.
//!
//! subql evaluates a [`RecordDescription`] against a row image and renders
//! each cell to the text a record is keyed on. rls2fga renders the same
//! records in SQL, with Postgres doing the rendering. Those two renderings
//! are written in different languages by different crates, so nothing but
//! running both against one database says they agree.
//!
//! The failure this catches is silent. A key rendered even slightly
//! differently, an integer with a thousands separator or a UUID in upper
//! case, names an object or a subject the store never contains, so every
//! answer about it is wrong and nothing reports a problem.
//!
//! rls2fga already proves its descriptions agree with its SQL, using its
//! own value rendering. That oracle stops where subql's adapter begins,
//! which is exactly the seam this covers.
//!
//! Docker-backed. Run with:
//!
//! ```sh
//! cargo test --test it visibility_records_parity:: \
//!     --features "visibility-records executor-diesel-postgres" -- --ignored --nocapture
//! ```

#![allow(clippy::unwrap_used)]

use crate::common;

use std::collections::BTreeSet;

use diesel::prelude::*;
use diesel::sql_types::{Integer, Text};
use diesel::{sql_query, PgConnection, QueryableByName};
use rls2fga::generator::well_known::can_select_relation;
use rls2fga::translator::TranslatorBuilder;
use rls2fga::types::ColumnName;
use rls2fga::types::ConfidenceLevel;
use rls2fga::types::RelationShapes;
use rls2fga::types::{BoundQuery, Record, RecordDerivation, RecordDescription, ReplayScope};
use sqlparser::dialect::PostgreSqlDialect;
use subql::backend::{CdcEvent, Postgres, RowKind, Value};
use subql::visibility::records::{is_evaluable, records_from_row_view};
use subql::visibility::shapes::Shapes;
use subql::visibility::store::{Enumeration, Requery};
use subql::visibility::EventRow;
use subql::{catalog_helpers, parse_wal2json_v2, MessageV2, ParserDB};

const SLOT: &str = "records_parity_slot";

/// The schema both sides read. Kept to statements `ParserDB` and rls2fga
/// both parse, so one string is the single source for the catalog, the
/// translation and the database.
///
/// Between them the five row-derived shapes cover every spelling
/// `render_text` claims: a `UUID` object key, an `INTEGER` and a `BIGINT`
/// one, a compound `INTEGER` pair, a `TEXT` subject, a JSON path subject, a
/// literal subject, and a boolean guard.
///
/// `readings` settles too: its clock guard lives in a condition the request
/// completes, so each row states one conditional record keyed on the whole
/// compound key.
const SCHEMA: &str = "
CREATE TABLE public.docs (id UUID PRIMARY KEY, owner_id TEXT, is_public BOOLEAN);
CREATE TABLE public.notes (id BIGINT PRIMARY KEY, owner_id TEXT);
CREATE TABLE public.cards (id INTEGER PRIMARY KEY, meta JSONB);
CREATE TABLE public.readings (tenant_id INTEGER, reading_id INTEGER, starts_at TIMESTAMPTZ,
    PRIMARY KEY (tenant_id, reading_id));
ALTER TABLE docs ENABLE ROW LEVEL SECURITY;
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE readings ENABLE ROW LEVEL SECURITY;
CREATE POLICY docs_owner ON docs FOR SELECT USING (owner_id = current_user);
CREATE POLICY docs_public ON docs FOR SELECT USING (is_public);
CREATE POLICY notes_owner ON notes FOR SELECT USING (owner_id = current_user);
CREATE POLICY cards_owner ON cards FOR SELECT USING (meta->>'owner' = current_user);
CREATE POLICY readings_started ON readings FOR SELECT USING (starts_at <= now());
";

// The typed schema for seeding. One `table!` per table above, so a column
// renamed in `SCHEMA` and not here is a compile error rather than a
// runtime one.
diesel::table! {
    docs (id) {
        id -> diesel::sql_types::Uuid,
        owner_id -> diesel::sql_types::Nullable<diesel::sql_types::Text>,
        is_public -> diesel::sql_types::Nullable<diesel::sql_types::Bool>,
    }
}

diesel::table! {
    notes (id) {
        id -> diesel::sql_types::BigInt,
        owner_id -> diesel::sql_types::Nullable<diesel::sql_types::Text>,
    }
}

diesel::table! {
    cards (id) {
        id -> diesel::sql_types::Integer,
        meta -> diesel::sql_types::Nullable<diesel::sql_types::Jsonb>,
    }
}

diesel::table! {
    readings (tenant_id, reading_id) {
        tenant_id -> diesel::sql_types::Integer,
        reading_id -> diesel::sql_types::Integer,
        starts_at -> diesel::sql_types::Nullable<diesel::sql_types::Timestamptz>,
    }
}

/// One `(object, relation, subject)` row of a tuple query.
///
/// The query text is generated by rls2fga at run time, so no `table!`
/// describes it and the typed DSL cannot express it. Naming the three
/// columns and their SQL types here is what keeps the raw statement from
/// drifting: a tuple query that stopped selecting `subject` would fail to
/// load rather than silently return less.
#[derive(QueryableByName)]
struct TupleRow {
    #[diesel(sql_type = Text)]
    object: String,
    #[diesel(sql_type = Text)]
    relation: String,
    #[diesel(sql_type = Text)]
    subject: String,
}

/// One row of a conditional tuple query, which projects five columns.
#[derive(QueryableByName)]
struct ConditionalTupleRow {
    #[diesel(sql_type = Text)]
    object: String,
    #[diesel(sql_type = Text)]
    relation: String,
    #[diesel(sql_type = Text)]
    subject: String,
    #[diesel(sql_type = Text)]
    condition: String,
    #[diesel(sql_type = diesel::sql_types::Jsonb)]
    context: serde_json::Value,
}

/// DDL, which the typed DSL does not express.
fn ddl(conn: &mut PgConnection, statement: &str) {
    sql_query(statement).execute(conn).expect(statement);
}

fn create_schema(conn: &mut PgConnection) {
    for statement in SCHEMA.split(';').filter(|s| !s.trim().is_empty()) {
        ddl(conn, statement);
    }
    // The update phase reads the previous image, which Postgres sends in
    // full only under FULL. Without this the difference is refused rather
    // than wrong, which would make that half of the test vacuous. `readings`
    // settles now too, so it needs the full image like the rest.
    for table in ["docs", "notes", "cards", "readings"] {
        ddl(conn, &format!("ALTER TABLE {table} REPLICA IDENTITY FULL"));
    }
}

fn uuid(text: &str) -> uuid::Uuid {
    uuid::Uuid::parse_str(text).unwrap()
}

fn timestamp(text: &str) -> chrono::DateTime<chrono::Utc> {
    chrono::DateTime::parse_from_rfc3339(text)
        .unwrap()
        .with_timezone(&chrono::Utc)
}

/// Rows chosen so each one answers a question the next cannot.
fn seed(conn: &mut PgConnection) {
    diesel::insert_into(docs::table)
        .values(vec![
            // Renders as a UUID, grants its owner, and is not public.
            (
                docs::id.eq(uuid("550e8400-e29b-41d4-a716-446655440000")),
                docs::owner_id.eq(Some("alice")),
                docs::is_public.eq(Some(false)),
            ),
            // A NULL owner grants nobody, and the public flag grants the
            // wildcard, so one row exercises both a failing and a passing
            // guard at once.
            (
                docs::id.eq(uuid("6ba7b810-9dad-11d1-80b4-00c04fd430c8")),
                docs::owner_id.eq(None::<&str>),
                docs::is_public.eq(Some(true)),
            ),
            // Punctuation a naive renderer might quote or escape. The colon
            // is the record separator, so a subject containing one is the
            // case most likely to be mangled on one side only.
            (
                docs::id.eq(uuid("00000000-0000-4000-8000-000000000001")),
                docs::owner_id.eq(Some("o'brien:x \"y\" ünïcode")),
                docs::is_public.eq(Some(false)),
            ),
        ])
        .execute(conn)
        .unwrap();

    diesel::insert_into(notes::table)
        .values(vec![
            // The extremes of the range subql decodes into `Value::Int`.
            (notes::id.eq(i64::MAX), notes::owner_id.eq(Some("bob"))),
            (notes::id.eq(i64::MIN), notes::owner_id.eq(Some("carol"))),
            (notes::id.eq(0_i64), notes::owner_id.eq(Some("dave"))),
        ])
        .execute(conn)
        .unwrap();

    diesel::insert_into(cards::table)
        .values(vec![
            // A string leaf reads as its contents, not its quoted form.
            (
                cards::id.eq(1),
                cards::meta.eq(Some(serde_json::json!({"owner": "erin"}))),
            ),
            // A number and a boolean leaf: `->>` renders both as text, and
            // so must the adapter.
            (
                cards::id.eq(2),
                cards::meta.eq(Some(serde_json::json!({"owner": 42}))),
            ),
            (
                cards::id.eq(3),
                cards::meta.eq(Some(serde_json::json!({"owner": true}))),
            ),
            // JSON null and an absent key both grant nobody.
            (
                cards::id.eq(4),
                cards::meta.eq(Some(serde_json::json!({"owner": null}))),
            ),
            (
                cards::id.eq(5),
                cards::meta.eq(Some(serde_json::json!({"other": "frank"}))),
            ),
            (cards::id.eq(6), cards::meta.eq(None::<serde_json::Value>)),
        ])
        .execute(conn)
        .unwrap();

    // Three rows arranged so neither column of the key identifies a row on
    // its own: two share `tenant_id`, two share `reading_id`. A query bound
    // to either column alone therefore returns a row that did not change,
    // which is the failure this fixture exists to expose.
    diesel::insert_into(readings::table)
        .values(vec![
            (
                readings::tenant_id.eq(1),
                readings::reading_id.eq(20),
                readings::starts_at.eq(Some(timestamp("2026-01-01T00:00:00Z"))),
            ),
            (
                readings::tenant_id.eq(1),
                readings::reading_id.eq(21),
                readings::starts_at.eq(Some(timestamp("2026-02-01T00:00:00Z"))),
            ),
            (
                readings::tenant_id.eq(2),
                readings::reading_id.eq(20),
                readings::starts_at.eq(Some(timestamp("2026-03-01T00:00:00Z"))),
            ),
        ])
        .execute(conn)
        .unwrap();
}

/// What the loader would write, straight from the database. A conditional
/// query's context arrives as the jsonb the loader wrote, respelled into the
/// text map subql renders, so the two spellings meet in one comparison.
fn records_from_sql(conn: &mut PgConnection, sql: &str, conditional: bool) -> BTreeSet<Fact> {
    if !conditional {
        return sql_query(sql)
            .load::<TupleRow>(conn)
            .unwrap_or_else(|error| panic!("tuple query failed: {error}\n{sql}"))
            .into_iter()
            .map(|row| (row.object, row.relation, row.subject, None))
            .collect();
    }
    sql_query(sql)
        .load::<ConditionalTupleRow>(conn)
        .unwrap_or_else(|error| panic!("conditional tuple query failed: {error}\n{sql}"))
        .into_iter()
        .map(|row| {
            let serde_json::Value::Object(fields) = row.context else {
                panic!("the loader writes a context as a JSON object: {sql}");
            };
            let values: std::collections::BTreeMap<String, String> = fields
                .into_iter()
                .map(|(key, value)| {
                    let text = match value {
                        serde_json::Value::String(text) => text,
                        other => other.to_string(),
                    };
                    (key, text)
                })
                .collect();
            (
                row.object,
                row.relation,
                row.subject,
                Some((row.condition, values)),
            )
        })
        .collect()
}

fn drain(conn: &mut PgConnection) -> Vec<MessageV2> {
    common::drain_slot(conn, SLOT)
        .iter()
        .flat_map(|line| parse_wal2json_v2(line.as_bytes()).unwrap())
        .collect()
}

/// One fact, as both sides can spell it, the condition and its context
/// values included so the rendering of a carried column is pinned too.
///
/// A relation name that came out of Postgres cannot be a `RelationName`: rls2fga
/// keeps that constructor crate-private so the type is proof its clamp and its
/// collision check both ran, and a string from a query is proof of neither. So
/// the comparison is over text, which is what the loader's SQL and subql's
/// rendering actually share.
type Fact = (
    String,
    String,
    String,
    Option<(String, std::collections::BTreeMap<String, String>)>,
);

fn fact(record: &Record) -> Fact {
    (
        record.object.clone(),
        record.relation.as_str().to_owned(),
        record.subject.clone(),
        record.context.as_ref().map(|context| {
            (
                context.condition.clone(),
                context.values.clone().into_iter().collect(),
            )
        }),
    )
}

/// Every record `description` implies over the `row` image of each event on
/// its table.
fn records_from_events(
    events: &[MessageV2],
    description: &RecordDescription,
    catalog: &ParserDB,
    row: RowKind,
) -> BTreeSet<Fact> {
    let RecordDerivation::FromRow { table, .. } = &description.derivation else {
        panic!("only a row-derived description reaches here");
    };
    let table =
        catalog_helpers::table_id(catalog, table.name()).expect("the table is in the catalog");

    let mut out = BTreeSet::new();
    for event in events {
        if event.table_id(catalog) != table {
            continue;
        }
        let Some(view) = EventRow::new(event, catalog, row) else {
            continue;
        };
        out.extend(
            records_from_row_view(description, &view, catalog)
                .unwrap_or_else(|error| {
                    panic!("subql refused a row it should read: {error}\n{description:#?}")
                })
                .iter()
                .map(fact),
        );
    }
    out
}

/// The descriptions rls2fga emits for `SCHEMA`, paired with the SQL that
/// loads each one.
fn shapes(catalog: &ParserDB) -> Vec<(String, bool, RecordDescription)> {
    let outputs = TranslatorBuilder::new()
        .with_min_confidence(ConfidenceLevel::B)
        .build()
        .translate(catalog)
        .expect("the parity schema translates")
        .outputs_accepting_gaps();
    outputs
        .tuple_queries()
        .iter()
        .filter_map(|query| {
            let description = query.description.clone()?;
            (is_evaluable::<Postgres, _>(&description, catalog)
                && matches!(description.derivation, RecordDerivation::FromRow { .. }))
            .then(|| (query.sql.clone(), query.condition.is_some(), description))
        })
        .collect()
}

#[test]
#[ignore = "requires Docker"]
fn every_record_a_row_implies_matches_the_query_that_loads_it() {
    common::assert_docker_available();
    let container = common::pg_with_wal2json();
    let mut pg = common::pg_connect(common::pg_port(&container));

    create_schema(&mut pg);
    common::create_slot(&mut pg, SLOT);
    seed(&mut pg);

    let catalog = ParserDB::parse::<PostgreSqlDialect>(SCHEMA).unwrap();
    let events = drain(&mut pg);
    assert!(!events.is_empty(), "the slot carried no row events");

    let shapes = shapes(&catalog);
    assert_eq!(shapes.len(), 5, "the schema should emit five shapes");

    let mut compared = 0usize;
    for (sql, conditional, description) in &shapes {
        let from_sql = records_from_sql(&mut pg, sql, *conditional);
        let from_rows = records_from_events(&events, description, &catalog, RowKind::New);
        assert_eq!(
            from_rows, from_sql,
            "subql's records diverge from the loader's for:\n{sql}"
        );
        compared += from_sql.len();
    }
    assert!(compared >= 8, "only {compared} records compared");
}

#[test]
#[ignore = "requires Docker"]
fn the_difference_a_change_reports_matches_what_the_loader_would_reload() {
    common::assert_docker_available();
    let container = common::pg_with_wal2json();
    let mut pg = common::pg_connect(common::pg_port(&container));

    create_schema(&mut pg);
    common::create_slot(&mut pg, SLOT);
    seed(&mut pg);
    drain(&mut pg);

    let catalog = ParserDB::parse::<PostgreSqlDialect>(SCHEMA).unwrap();
    let shapes = shapes(&catalog);
    let before: BTreeSet<Fact> = shapes
        .iter()
        .flat_map(|(sql, conditional, _)| records_from_sql(&mut pg, sql, *conditional))
        .collect();

    // One row changes hands, one loses its grant, one gains one, and one is
    // removed outright, so the difference has to carry all four directions.
    diesel::update(docs::table.find(uuid("550e8400-e29b-41d4-a716-446655440000")))
        .set(docs::owner_id.eq(Some("zara")))
        .execute(&mut pg)
        .unwrap();
    diesel::update(notes::table.find(i64::MAX))
        .set(notes::owner_id.eq(None::<&str>))
        .execute(&mut pg)
        .unwrap();
    diesel::update(cards::table.find(5))
        .set(cards::meta.eq(Some(serde_json::json!({"owner": "gina"}))))
        .execute(&mut pg)
        .unwrap();
    diesel::delete(notes::table.find(0_i64))
        .execute(&mut pg)
        .unwrap();

    let events = drain(&mut pg);
    assert_eq!(events.len(), 4, "one event per statement");

    let after: BTreeSet<Fact> = shapes
        .iter()
        .flat_map(|(sql, conditional, _)| records_from_sql(&mut pg, sql, *conditional))
        .collect();

    let outputs = TranslatorBuilder::new()
        .with_min_confidence(ConfidenceLevel::B)
        .build()
        .translate(&catalog)
        .expect("the parity schema translates")
        .outputs_accepting_gaps();
    let relations = outputs.translation().relations().to_vec();
    let enumerations: Vec<Enumeration<'_>> = outputs
        .tuple_queries()
        .iter()
        .filter_map(|query| {
            query.description.as_ref().map(|description| Enumeration {
                description,
                sql: &query.sql,
                condition: query.condition.as_deref(),
            })
        })
        .collect();
    let store = Shapes::new::<Postgres>(
        ParserDB::parse::<PostgreSqlDialect>(SCHEMA).unwrap(),
        &relations,
        &enumerations,
    );
    assert!(store.uncovered().is_empty(), "{:?}", store.uncovered());

    let mut added = BTreeSet::new();
    let mut removed = BTreeSet::new();
    for event in &events {
        let diff = store
            .diff(event)
            .unwrap_or_else(|error| panic!("the difference was refused: {error}"));
        added.extend(diff.added.iter().map(fact));
        removed.extend(diff.removed.iter().map(fact));
        assert!(
            diff.requeries.is_empty(),
            "these events are on tables no query is bound to"
        );
    }

    assert_eq!(
        added,
        after.difference(&before).cloned().collect::<BTreeSet<_>>(),
        "what the rows say was added is not what the loader would now write"
    );
    assert_eq!(
        removed,
        before.difference(&after).cloned().collect::<BTreeSet<_>>(),
        "what the rows say was removed is not what the loader would now drop"
    );
    assert!(
        !added.is_empty() && !removed.is_empty(),
        "vacuous comparison"
    );
}

/// The integer a key column of `meters` carries, in the type the `table!`
/// above declares for it.
fn key_int(value: &Value<Postgres>) -> i32 {
    match value {
        Value::Int(int) => i32::try_from(*int).expect("an INTEGER key fits an i32"),
        other => panic!("a key column of meters is an integer, not {other:?}"),
    }
}

fn column(name: &str) -> ColumnName {
    serde_json::from_value(serde_json::Value::String(name.to_owned()))
        .expect("the column name deserializes")
}

/// A gated membership over a table two columns identify together, which still
/// answers by replaying. The deciding rows live on `meter_members`, so no row
/// of `meters` settles it.
const GRANTS_SCHEMA: &str = "
CREATE TABLE public.meters (tenant_id INTEGER, meter_id INTEGER, label TEXT NOT NULL,
    PRIMARY KEY (tenant_id, meter_id));
CREATE TABLE public.meter_members (tenant_id INTEGER, meter_id INTEGER, user_id TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL, FOREIGN KEY (tenant_id, meter_id) REFERENCES meters(tenant_id, meter_id));
ALTER TABLE meters ENABLE ROW LEVEL SECURITY;
CREATE POLICY meters_member ON meters FOR SELECT USING (
    EXISTS (SELECT 1 FROM meter_members
            WHERE meter_members.tenant_id = meters.tenant_id
              AND meter_members.meter_id = meters.meter_id
              AND meter_members.user_id = current_user
              AND meter_members.expires_at > now()));
";

diesel::table! {
    meters (tenant_id, meter_id) {
        tenant_id -> diesel::sql_types::Integer,
        meter_id -> diesel::sql_types::Integer,
        label -> diesel::sql_types::Text,
    }
}

fn compound_replay_relations(catalog: &ParserDB) -> Vec<RelationShapes> {
    let translated = TranslatorBuilder::new()
        .with_min_confidence(ConfidenceLevel::B)
        .build()
        .translate(catalog)
        .expect("the grants schema translates")
        .relations()
        .to_vec();
    let meters_type = translated
        .iter()
        .find(|relation| relation.type_name == "meters")
        .expect("the model names meters")
        .type_name
        .clone();
    let relation = can_select_relation();
    vec![RelationShapes {
        type_name: meters_type.clone(),
        relation: relation.clone(),
        from_one_row: false,
        shapes: vec![RecordDescription {
            tables: vec![rls2fga::types::TableId::from_stored(
                None,
                "meter_members".to_owned(),
            )],
            derivation: RecordDerivation::Joined {
                queries: vec![BoundQuery::new(
                    rls2fga::types::TableId::from_stored(None, "meter_members".to_owned()),
                    vec![column("tenant_id"), column("meter_id")],
                    "SELECT 'meters:' || tenant_id::text || '|' || meter_id::text AS object, \
                     'can_select' AS relation, 'user:' || user_id::text AS subject \
                     FROM meter_members WHERE tenant_id = $1 AND meter_id = $2"
                        .to_owned(),
                    None,
                    ReplayScope::Object {
                        object_type: meters_type,
                        relations: vec![relation],
                    },
                )
                .expect("the fixture query binds its key")],
                reason: "compound replay fixture".to_owned(),
            },
        }],
        decision: None,
        grants_nobody: false,
    }]
}

/// The query handed over for a two-column key selects the row that changed,
/// and only it.
///
/// Nothing else proves the values and the placeholders agree. subql reads the
/// values off the row image, rls2fga writes the placeholders into the SQL, and
/// the two meet nowhere until Postgres runs the statement. A key bound in the
/// wrong order returns the wrong row or none, and a key short of a column is
/// refused by Postgres outright.
#[test]
#[ignore = "requires Docker"]
fn a_replayed_compound_key_query_selects_only_the_row_that_changed() {
    common::assert_docker_available();
    let container = common::pg_with_wal2json();
    let mut pg = common::pg_connect(common::pg_port(&container));

    for statement in GRANTS_SCHEMA.split(';').filter(|s| !s.trim().is_empty()) {
        ddl(&mut pg, statement);
    }
    common::create_slot(&mut pg, SLOT);
    diesel::insert_into(meters::table)
        .values(vec![
            (
                meters::tenant_id.eq(1),
                meters::meter_id.eq(20),
                meters::label.eq("old"),
            ),
            (
                meters::tenant_id.eq(1),
                meters::meter_id.eq(21),
                meters::label.eq("sibling"),
            ),
        ])
        .execute(&mut pg)
        .unwrap();
    sql_query(
        "INSERT INTO meter_members (tenant_id, meter_id, user_id, expires_at) VALUES \
         (1, 21, 'dave', '2027-01-01T00:00:00Z')",
    )
    .execute(&mut pg)
    .unwrap();
    drain(&mut pg);

    sql_query(
        "INSERT INTO meter_members (tenant_id, meter_id, user_id, expires_at) VALUES \
         (1, 20, 'carol', '2027-01-01T00:00:00Z')",
    )
    .execute(&mut pg)
    .unwrap();

    let events = drain(&mut pg);
    assert_eq!(events.len(), 1, "one event for one statement");
    let catalog = ParserDB::parse::<PostgreSqlDialect>(GRANTS_SCHEMA).unwrap();

    let relations = compound_replay_relations(&catalog);
    let store = Shapes::new::<Postgres>(catalog, &relations, &[]);

    let diff = store
        .diff(&events[0])
        .unwrap_or_else(|error| panic!("the difference was refused: {error}"));
    assert!(
        !diff.requeries.is_empty(),
        "the change must hand over at least one replay: {diff:?}"
    );
    for requery in &diff.requeries {
        let Requery::Keyed(keyed) = requery else {
            panic!("expected KeyedRequery, got Whole materialisation");
        };
        assert_eq!(keyed.query.table().name(), "meter_members");
        assert_eq!(keyed.query.key_columns(), ["tenant_id", "meter_id"]);

        let rows = sql_query(keyed.query.sql())
            .bind::<Integer, _>(key_int(&keyed.key[0]))
            .bind::<Integer, _>(key_int(&keyed.key[1]))
            .load::<TupleRow>(&mut pg)
            .unwrap_or_else(|error| {
                panic!("the replayed query failed: {error}\n{}", keyed.query.sql())
            });

        assert!(
            !rows.is_empty(),
            "the replay returns the changed row's facts:\n{}",
            keyed.query.sql()
        );
        for row in &rows {
            assert_eq!(
                row.object,
                "meters:1|20",
                "the whole key names the changed row and no other:\n{}",
                keyed.query.sql()
            );
        }
    }
}
